### Ai 메시지 생성
POST http://localhost:10000/internal/v1/ai-messages
Content-Type: application/json

{
  "ai": {
    "prompt": "Name: John Doe\nEmail: johndoe@example.com\nPhone Number: 555-555-5555\n Order Number: 1234\nOrder Total: $50.00\n 100자 이내로 주문 알림 생성해줘. \n\n"
  }
}