server:
  port: 14001

spring:
  application:
    name: alarm-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/alarm
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: alarm-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  server:
    port: 14001
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
#      slo:
#        http.server.requests: 50ms, 100ms, 200ms

slack:
  webhook:
    url: https://hooks.slack.com/services/
    key: ${WEBHOOK-KEY}
    "display_information":
      "name": "Musinsam Alarmbot"
    "settings":
      "org_deploy_enabled": false,
      "socket_mode_enabled": false,
      "is_hosted": false,
      "token_rotation_enabled": false
  userlist:
    url: https://slack.com/api/users.list
  conversations:
    open:
      url: https://slack.com/api/conversations.open
  chat:
    postMessage:
      url: https://slack.com/api/chat.postMessage
  bot-token: ${BOT-TOKEN}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
