spring:
  application:
    name: coupon-service

  config:
    import:
      - optional:file:.env.coupon[.properties]
      - classpath:properties/base.yml
      - classpath:properties/cloud.yml
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
  profiles:
    group:
      local: local
      develop: develop
    active: develop
