server:
  port: 15001

spring:
  application:
    name: ai-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/ai
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
  config:
    import:
      - optional:file:.env

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  server:
    port: 15001
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms

openai:
  api:
    key: ${OPENAI-API-KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
