global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus-alarm'
    static_configs:
      - targets: [ 'localhost:9094' ]

  - job_name: 'alarm-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.localhost:10054' ]