server:
  port: 10000

spring:
  application:
    name: eureka-gateway

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: public-auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /v1/auth/signup, /v1/auth/login, /v1/auth/logout, /v1/auth/generate-token

        - id: internal-user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/internal/v1/users/**

        - id: swagger-user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/users/**

        - id: internal-ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/internal/v1/ai-messages/**

        - id: swagger-ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/ai-service/v3/api-docs
          filters:
            - RewritePath=/ai-service/v3/api-docs, /v3/api-docs

        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/v1/ai-messages/**

        - id: internal-alarm-service
          uri: lb://ALARM-SERVICE
          predicates:
            - Path=/internal/v1/slack-alarms/**

        - id: swagger-alarm-service
          uri: lb://ALARM-SERVICE
          predicates:
            - Path=/alarm-service/v3/api-docs
          filters:
            - RewritePath=/alarm-service/v3/api-docs, /v3/api-docs

        - id: alarm-service
          uri: lb://ALARM-SERVICE
          predicates:
            - Path=/v1/slack-alarms/**

        - id: internal-coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/internal/v1/coupons/**

        - id: swagger-coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/coupon-service/v3/api-docs
          filters:
            - RewritePath=/coupon-service/v3/api-docs, /v3/api-docs

        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/v1/coupons/**

        - id: coupon-Policy-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/v1/coupon-policies/**

        - id: internal-event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/internal/v1/events/**

        - id: swagger-event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event-service/v3/api-docs
          filters:
            - RewritePath=/event-service/v3/api-docs, /v3/api-docs

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/v1/events/**

        - id: internal-order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/internal/v1/orders/**

        - id: swagger-order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/v3/api-docs
          filters:
            - RewritePath=/order-service/v3/api-docs, /v3/api-docs

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/orders/**

        - id: internal-payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/internal/v1/payments/**

        - id: swagger-payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/v3/api-docs
          filters:
            - RewritePath=/payment-service/v3/api-docs, /v3/api-docs

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/v1/payments/**

        - id: internal-product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/internal/v1/products/**

        - id: swagger-product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/v3/api-docs
          filters:
            - RewritePath=/product-service/v3/api-docs, /v3/api-docs

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/products/**

        - id: internal-shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/internal/v1/shops/**

        - id: swagger-shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shop-service/v3/api-docs
          filters:
            - RewritePath=/shop-service/v3/api-docs, /v3/api-docs

        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/v1/shops/**

      discovery:
        locator:
          enabled: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1

auth:
  whitelist:
    - /internal/**
    - /v1/auth/signup
    - /v1/auth/login
    - /v1/auth/logout
    - /v1/auth/generate-token
    - /swagger-ui/**
    - /v3/api-docs/**
    - /swagger-resources/**
    - /webjars/**
    - /user-service/v3/api-docs
    - /ai-service/v3/api-docs
    - /alarm-service/v3/api-docs
    - /coupon-service/v3/api-docs
    - /event-service/v3/api-docs
    - /order-service/v3/api-docs
    - /payment-service/v3/api-docs
    - /product-service/v3/api-docs
    - /shop-service/v3/api-docs

springdoc:
  swagger-ui:
    use-root-path: true
    urls[0]:
      name: USER-SERVICE
      url: /user-service/v3/api-docs
    urls[1]:
      name: COUPON-SERVICE
      url: /coupon-service/v3/api-docs
    urls[2]:
      name: AI-SERVICE
      url: /ai-service/v3/api-docs
    urls[3]:
      name: ALARM-SERVICE
      url: /alarm-service/v3/api-docs
    urls[4]:
      name: SHOP-SERVICE
      url: /shop-service/v3/api-docs
    urls[5]:
      name: EVENT-SERVICE
      url: /event-service/v3/api-docs
    urls[6]:
      name: ORDER-SERVICE
      url: /order-service/v3/api-docs
    urls[7]:
      name: PAYMENT-SERVICE
      url: /payment-service/v3/api-docs
    urls[8]:
      name: PRODUCT-SERVICE
      url: /product-service/v3/api-docs