server:
  port: 12001

spring:
  application:
    name: order-service

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 3000
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.highlight_sql: true
      use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      product-service:
        max-attempts: 3
        wait-duration: 500ms

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,info,prometheus,metrics

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    com.musinsam.orderservice: DEBUG
