### 1. 회원가입
POST http://localhost:10001/v1/auth/signup
Content-Type: application/json

{
  "user": {
    "email": "alice2@gmail.com",
    "password": "Authorize123!",
    "name": "alice2",
    "userRoleType": "ROLE_COMPANY"
  }
}

### 2. 로그인 (토큰 발급)
POST http://localhost:10001/v1/auth/login
Content-Type: application/json

{
  "user": {
    "email": "alice2@gmail.com",
    "password": "Authorize123!"
  }
}

> {%
  client.global.set("accessToken", response.body.data.token.accessToken);
  client.global.set("userId", response.body.data.user.userId);
  client.global.set("userRole", response.body.data.user.userRoleType);
%}

### 상점 등록 테스트
POST http://localhost:10000/v1/shops
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

{
  "shop": {
    "userId": 1,
    "name": "nike"
  }
}

### 상점 목록 조회 테스트
GET http://localhost:10000/v1/shops?page=0&size=10&orderby=CREATED&sort=DESC
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

### 상점 상세 조회 테스트
GET http://localhost:10000/v1/shops/af80aa19-9c74-49dc-b115-8f4533de0f7b
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

### 상점 수정 테스트
PUT http://localhost:10000/v1/shops/66abd648-b994-494d-90bb-1a5b984010f6
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

{
  "shop": {
    "name": "adidas"
  }
}

### 상점 삭제 테스트
DELETE http://localhost:10000/v1/shops/66abd648-b994-494d-90bb-1a5b984010f6
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

### 상점 단건 조회 테스트 (내부용)
GET http://localhost:10000/internal/v1/shops/af80aa19-9c74-49dc-b115-8f4533de0f7b
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 상점 검색 테스트 (내부용)
GET http://localhost:10000/internal/v1/shops/search
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 1
}

### 상점에 적용된 쿠폰 조회 (내부용)
GET http://localhost:10000/internal/v1/shops/coupons?shopId=af80aa19-9c74-49dc-b115-8f4533de0f7b
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 배치 실행 API (테스트용)
POST http://localhost:10000/internal/v1/shops/batch/weekly-coupon
Content-Type: application/json
Authorization: Bearer {{accessToken}}

