### 상점 등록 테스트
POST http://localhost:11003/v1/shops
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: ROLE_COMPANY
#Authorization: Bearer {{accessToken}}

{
  "shop": {
    "userId": 1,
    "name": "nike"
  }
}

### 상점 목록 조회 테스트
GET http://localhost:11003/v1/shops?page=0&size=10&orderby=CREATED&sort=DESC
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: ROLE_COMPANY

### 상점 상세 조회 테스트
GET http://localhost:11003/v1/shops/af80aa19-9c74-49dc-b115-8f4533de0f7b
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: ROLE_COMPANY

### 상점 수정 테스트
PUT http://localhost:11003/v1/shops/af80aa19-9c74-49dc-b115-8f4533de0f7b
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: ROLE_COMPANY

{
  "shop": {
    "name": "adidas"
  }
}

### 상점 삭제 테스트
DELETE http://localhost:11003/v1/shops/af80aa19-9c74-49dc-b115-8f4533de0f7b
Content-Type: application/json
X-USER-ID: 1
X-USER-ROLE: ROLE_COMPANY