### 1. 회원가입
POST http://localhost:10001/v1/auth/signup
Content-Type: application/json

{
  "user": {
    "email": "alice@gmail.com",
    "password": "Authorize123!",
    "name": "alice",
    "userRoleType": "ROLE_MASTER"
  }
}

### 2. 로그인 (토큰 발급)
POST http://localhost:10001/v1/auth/login
Content-Type: application/json

{
  "user": {
    "email": "alice@gmail.com",
    "password": "Authorize123!"
  }
}

> {%
  client.global.set("accessToken", response.body.data.token.accessToken);
  client.global.set("userId", response.body.data.user.userId);
  client.global.set("userRole", response.body.data.user.userRoleType);
%}

### 알림 등록 테스트
POST http://localhost:10000/internal/v1/slack-alarms
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

{
  "alarm": {
    "message": "Name: John Doe\nEmail: johndoe@example.com\nPhone Number: 555-555-5555\n Order Number: 1234\nOrder Total: $50.00\nMessage: Urgent - Please check on the status of my order.\n\n"
  }
}

### 알림 전체 조희 테스트
GET http://localhost:10000/internal/v1/slack-alarms?page=0&size=10&orderby=CREATED&sort=DESC
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}

### 알림 단건 조희 테스트
GET http://localhost:10000/internal/v1/slack-alarms/76a5abec-741d-403d-b6c5-3a2f01f802ff
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-User-Id: {{userId}}
X-User-Role: {{userRole}}
