### 1. 회원가입
POST http://localhost:10001/v1/auth/signup
Content-Type: application/json

{
  "user": {
    "email": "alice@gmail.com",
    "password": "Authorize123!",
    "name": "alice",
    "userRoleType": "ROLE_MASTER"
  }
}

### 2. 로그인 (토큰 발급)
POST http://localhost:10001/v1/auth/login
Content-Type: application/json

{
  "user": {
    "email": "alice@gmail.com",
    "password": "Authorize123!"
  }
}

> {%
  client.global.set("accessToken", response.body.data.token.accessToken);
  client.global.set("userId", response.body.data.user.userId);
  client.global.set("userRole", response.body.data.user.userRoleType);
%}

### 알림 등록 테스트
POST http://localhost:10000/internal/v1/slack-alarms
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "alarm": {
    "message": "오늘부터 2025년 5월 31일까지, 선착순으로 제공되는 쿠폰이 등장했습니다! 지금 이 매장에서 쇼핑을 하시면, 15% 할인 혜택을 누리실 수 있어요. 얼른 확인해보세요!"
  }
}

### 알림 전체 조희 테스트
GET http://localhost:10000/internal/v1/slack-alarms?page=0&size=10&orderby=CREATED&sort=DESC
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 알림 단건 조희 테스트
GET http://localhost:10000/internal/v1/slack-alarms/76a5abec-741d-403d-b6c5-3a2f01f802ff
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 슬랙 USERID 조회
GET https://slack.com/api/users.lookupByEmail?email=soo0864@gmail.com
Authorization: Bearer {{botToken}}

### 슬랙 전체 유저 리스트에서 찾기
GET https://slack.com/api/users.list
Authorization: Bearer {{botToken}}

### 슬랙 DM 채널 열기
POST https://slack.com/api/conversations.open
Authorization: Bearer {{botToken}}
Content-Type: application/json

{
  "users": "U08LC8E2JVC"
}