services:
  redis-user:
    image: redis:latest
    container_name: redis-user
    ports:
      - "6379:6379"
    volumes:
      - ./redis-user-config:/usr/local/etc/redis
    networks:
      - laboratory-network

  redis-coupon:
    image: redis:latest
    container_name: redis-coupon
    ports:
      - "6380:6379"
    volumes:
      - ./redis-coupon-config:/usr/local/etc/redis
    networks:
      - laboratory-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Seoul
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laboratory-network

volumes:
  postgres_data:

networks:
  laboratory-network:
    driver: bridge
