### Local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/musinsam
    username: musinsam
    password: musinsam


---
### Container
spring:
  config:
    activate:
      on-profile: container

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${CONTAINER_DB_URL}
    username: ${CONTAINER_DB_USERNAME}
    password: ${CONTAINER_DB_PASSWORD}


---
### Test
spring:
  config:
    activate:
      on-profile: test


---
### Production
spring:
  config:
    activate:
      on-profile: prod