### Local
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false

---
### Container
spring:
  config:
    activate:
      on-profile: container

---
### Test
spring:
  config:
    activate:
      on-profile: test

---
### Production
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false